series:
  720_Group:
    - Adventure Time
    - Aquarius US
    - Arrow
    - Banchee
    - Blindspot
    - Constantine
    - Continuum
    - DC's Legends Of Tomorrow
    - Damien
    - Dark Matter
    - Dig
    - Doctor Who 2005
    - Falling Skies
    - Fear The Walking Dead
    - Game of Thrones
    - Guardians of the Galaxy
    - Into The Badlands
    - Killjoys
    - Limitless
    - Lucifer
    - Marvel's Agents of S.H.I.E.L.D.
    - Mr Robot
    - Quantico
    - Scorpion
    - Silicon Valley
    - Stitchers
    - Suits
    - Supergirl
    - The 100
    - The Bastard Executioner
    - The Big Bang Theory
    - The Flash
    - The Last Man on Earth
    - The Last Ship 
    - The Librarians
    - The Man In The High Castle
    - The Messengers
    - The Romeo Section
    - The Simpsons
    - The Walking Dead
    - The X-Files
    - True Detective
    - Van Helsing
    - Westworld
    - iZombie
  480_Group:
    - 12 Monkeys
    - 800 Words
    - Almost Human
    - American Dad!
    - Angel From Hell
    - Archer
    - Atlantis
    - Battle Creek
    - Better Call Saul
    - Black Work
    - Boardwalk Empire
    - Bones
    - Braindead
    - Brotherhood
    - CSI Cyber
    - Car SOS
    - Chicago PD
    - Code Black
    - Covert Affairs
    - Criminal Minds
    - Crowded
    - Da Vinci's Demons
    - Dara O Briains Go 8Bit
    - Defiance
    - Dickensian
    - Doctor Foster
    - Dominion
    - Dracula
    - Elementary
    - Faking it
    - Family Guy
    - Fortitude
    - Garage Squad
    - Gotham
    - Grandfathered
    - Greenleaf
    - Guilt
    - Houdini and Doyle
    - It's Always Sunny in
    - Jeff Dunham
    - Jimmy Fallon
    - Jonathan Creek
    - Jonathan Strange And Mr Norrell
    - Life in Pieces
    - Man Finds Food
    - Man Vs Food
    - Masters of Sex
    - Mercy Street
    - Mum
    - NCIS
    - NCIS Los Angeles
    - New Blood
    - New Girl
    - Odd Mom Out
    - Once Upon A Time
    - Orphan Black
    - Outlander
    - Penny Dreadful
    - Public Morals
    - Queen of the South
    - Ray Donovan
    - Resurrection
    - Revolution
    - Roadies
    - Rookie Blue
    - Rosewood
    - Secret City
    - Secrets and Lies
    - Shadowhunters
    - Sherlock
    - Significant Mother
    - Sleepy Hollow
    - Smoked
    - Sons of Anarchy
    - Still The King
    - Superstore
    - The A Word
    - The Americans
    - The Blacklist
    - The Leftovers
    - The Listener
    - The Odd Couple
    - The Originals
    - The Path
    - The Real O'Neals
    - The Secret Life of An American Teenager
    - This Life
    - The Whispers
    - Top Gear
    - Under The Dome
    - Vikings
    - Vinyl
    - Wasted
    - Wayward Pines
    - Weird Loners
    - Wheeler Dealers
    - White Queen
    - X Company
    - You me and the apocalypse
    - Young Hyacinth
    - Younger
#    - A Cook Abroad
#    - Ashes to Ashes
#    - Australias Cheapest Weddings
#    - Awkward
#    - Back in time for dinner
#    - Castle 2009
#    - Clipped
#    - Cooper Barretts Guide to Surviving Life
#    - Fuller House
#    - Kevin From Work
#    - Len and Ainsleys Big Food Adventure
#    - Mr Robinson
#    - One Big Happy
#    - Recovery Road
#    - Revenge
#    - Safehouse
#    - Scream Queens
#    - The Astronaut Wives Club
#    - The Lizzie Borden Chronicles
#    - The Millers
#    - The Slap (US)